### PR TITLE
[WIP] Add Japanese locale

### PR DESCRIPTION
**Pull request by yasulab**
Thanks @xdamman for giving me a chance to translate into Japanese. ;)
I am adding Japanese locale, which is still rough for now, but I will revise it later. :memo: :dash:

### CODE REVIEW

**Comment by xdamman** [comment]
Any update on this? You should pull the latest from master as there has been a couple of new additions to the language files. Don't forget to add a line at the end of that file for `jp` https://github.com/opencollective/frontend/blob/master/scripts/translate.js#L47 and then run `npm run build:langs`.

**Comment by yasulab** [comment]
Thanks for letting me know it. ;) I have been busy for a while, but I'm planning to finish this translation until 20th! 📝 💨 Thanks for your patience. 🙏

**Comment by yasulab** [comment]
Hi, I have resumed and am working on this translation! 💨 

One question. I'm not sure the translated words are fit into a right context because Japanese words often vary depending on a context.

Can I update my translation after deploying it, especially if I find something that should be updated?

**Comment by xdamman** [comment]
Pushing it now to production!

**Comment by xdamman** [comment]
Looking good!


Note that there are new strings to translate: https://github.com/opencollective/frontend/pull/119

**Comment by yasulab** [comment]
Thanks for deploying it! 😸 I'll check out production site and keep upgrading Japanese locales and send another PR 🔧 💨

**Pull request merged**
