### PR TITLE
Nametags

### PR DESCRIPTION
**Pull request by xdamman**
New route: `/:collectiveSlug/events/:eventSlug/nametags.pdf`

Todo: add support for US format and different name tag sizes

### CODE REVIEW

**Comment by jdorfman** [comment]
checking with Gunner

**Comment by alnermcgunn** [comment]
We just want first name, *no other participant data*, in the largest possible font. 

No last name, no title, no affiliation. 

Fine and/or desirable to have event name/location/dates etc in small type at e.g. bottom of name tag.

Re-attaching our template as a reference, you can ignore the logo.

Thanks!

[AspirationEventNametagTemplate.pdf](https://github.com/opencollective/frontend/files/1064900/AspirationEventNametagTemplate.pdf)

**Comment by jdorfman** [comment]
@xdamman good?

**Comment by xdamman** [comment]
Yep. https://github.com/opencollective/frontend/pull/16

**Comment by xdamman** [comment]
eg. https://opencollective.com/sustainoss/events/2017/nametags.pdf

with the marks: https://opencollective.com/sustainoss/events/2017/nametags.pdf?template=showMarks

**Comment by alnermcgunn** [comment]
These look great, thank you so much. 

Only question to other organizers is do we want event name in the footer?

**Comment by jdorfman** [comment]
@xdamman Looks amazing

@alnermcgunn I would like the Event (SustainOSS) in the footer. I keep my badges for sentimental reasons (as others do).

@xdamman if it isn't too much trouble, that would be awesome. =)

**Comment by xdamman** [comment]
Sure thing.

Right now the name of the event is simply "Sustain". Happy to change it to "SustainOSS"

**Comment by jdorfman** [comment]
Omg looks amazing. Good catch, it should just be Sustain. ❤️

**Pull request merged**
