### PR TITLE
fix: display hashtag or handle

### PR DESCRIPTION
**Pull request by znck**
Display `#foo` or `@foo` depending upon `twitterHandle` value.

### CODE REVIEW

**Comment by xdamman** [comment]
Hey, thanks for contributing! :-)

What's the use case for this? Can you give an example?
Also in that case, the link should be different no? twitter.com/#hashtag doesn't work. Should be https://twitter.com/search?q=%23hashtag

**Comment by znck** [comment]
Example: https://twitter.com/hashtag/webpack 
I'm also using #VueBLR for a meetup group. It should allow hashtag too.

**Comment by znck** [comment]
Though the PR is very naive fix. If wish to include it, I can improve it.

**Comment by xdamman** [comment]
Closing this for now. It's confusing to have `twitterHandle` to represent a hashtag. I'd rather see a new column in the model `hashtag`. That requires a larger PR (you can look at other examples of PR to add such column, eg. https://github.com/opencollective/opencollective-api/pull/837/files

**Pull request closed without merging**
