### PR TITLE
Fix collective to collective navigation

### PR DESCRIPTION
**Pull request by znarf**
Navigating from Collective to Collective could be broken, especially when there was no loading state while transitioning from one to the other.

That was easily reproducible, going from one collective, to another collective, then using the back button from the browser.

Related issue: #308

### CODE REVIEW

**Comment by xdamman** [comment]
Where did the mutation go?
Can you explain why we don't need withData when exporting this component?

**Comment by znarf** [comment]
@xdamman I could not see how the mutation was used, so I figured this was dead code. Let me know if I'm wrong.

I didn't touch or remove withData, this is provided by the CollectivePage, which is passing the data to this component as props.

**Comment by xdamman** [comment]
ah ok good catch!

**Review by priyadiwidjaja — APPROVED** [review]

**Pull request merged**
