### PR TITLE
feat(expenses): Allow to donate in kind with expenses

### PR DESCRIPTION
**Pull request by clarete**

### CODE REVIEW

**Comment by clarete** [comment]
@znarf this looks awesome!

**Comment by znarf** [comment]
@clarete I'm not actually happy with the outcome today, but it looks promising.

Let's figure how to make it works great for us!

**Comment by clarete** [comment]
The semantic release bot? I thought it was kinda neat to know in which version a given PR gets merged.

**Comment by znarf** [comment]
Yes, the problems I had were that:
- it's not triggered at the right moment (was on any merge on master)
- it was not detecting properly our version, and not taking care of bumping the version in package.json

**Comment by clarete** [comment]
That's a great breakdown! And yep these fixes will certainly look great! \o/

**Pull request merged**
